export const ENVIRONMENT_VARIABLES = {
  nodeEnv: 'NODE_ENV',
  host: 'HOST',
  port: 'PORT',
  logLevel: 'LOG_LEVEL',
  corsOrigins: 'CORS_ORIGINS',
  databaseUrl: 'DATABASE_URL',
  databasePoolMax: 'DATABASE_POOL_MAX',
  databasePoolIdleTimeoutMs: 'DATABASE_POOL_IDLE_TIMEOUT_MS',
  databasePoolConnectionTimeoutMs: 'DATABASE_POOL_CONNECTION_TIMEOUT_MS',
  redisUrl: 'REDIS_URL',
  redisKeyPrefix: 'REDIS_KEY_PREFIX',
  redisConnectTimeoutMs: 'REDIS_CONNECT_TIMEOUT_MS',
  redisCommandTimeoutMs: 'REDIS_COMMAND_TIMEOUT_MS',
  redisMaxRetriesPerRequest: 'REDIS_MAX_RETRIES_PER_REQUEST',
  jobsQueueName: 'JOBS_QUEUE_NAME',
  jobsAttempts: 'JOBS_ATTEMPTS',
  jobsBackoffDelayMs: 'JOBS_BACKOFF_DELAY_MS',
  jobsBackoffJitter: 'JOBS_BACKOFF_JITTER',
  jobsWorkerConcurrency: 'JOBS_WORKER_CONCURRENCY',
  jobsLockDurationMs: 'JOBS_LOCK_DURATION_MS',
  jobsMaxStalledCount: 'JOBS_MAX_STALLED_COUNT',
  jobsRemoveOnCompleteAgeSeconds: 'JOBS_REMOVE_ON_COMPLETE_AGE_SECONDS',
  jobsRemoveOnCompleteCount: 'JOBS_REMOVE_ON_COMPLETE_COUNT',
  jobsRemoveOnFailAgeSeconds: 'JOBS_REMOVE_ON_FAIL_AGE_SECONDS',
  jobsRemoveOnFailCount: 'JOBS_REMOVE_ON_FAIL_COUNT',
  outboxPollIntervalMs: 'OUTBOX_POLL_INTERVAL_MS',
  outboxBatchSize: 'OUTBOX_BATCH_SIZE',
  processShutdownTimeoutMs: 'PROCESS_SHUTDOWN_TIMEOUT_MS',
  trustedProxyCidrs: 'TRUSTED_PROXY_CIDRS',
  rateLimitGlobalLimit: 'RATE_LIMIT_GLOBAL_LIMIT',
  rateLimitGlobalTtlMs: 'RATE_LIMIT_GLOBAL_TTL_MS',
  rateLimitGlobalBlockMs: 'RATE_LIMIT_GLOBAL_BLOCK_MS',
  rateLimitAuthLimit: 'RATE_LIMIT_AUTH_LIMIT',
  rateLimitAuthTtlMs: 'RATE_LIMIT_AUTH_TTL_MS',
  rateLimitAuthBlockMs: 'RATE_LIMIT_AUTH_BLOCK_MS',
  rateLimitAccountLimit: 'RATE_LIMIT_ACCOUNT_LIMIT',
  rateLimitAccountTtlMs: 'RATE_LIMIT_ACCOUNT_TTL_MS',
  rateLimitAccountBlockMs: 'RATE_LIMIT_ACCOUNT_BLOCK_MS',
  rateLimitWebhookLimit: 'RATE_LIMIT_WEBHOOK_LIMIT',
  rateLimitWebhookTtlMs: 'RATE_LIMIT_WEBHOOK_TTL_MS',
  rateLimitWebhookBlockMs: 'RATE_LIMIT_WEBHOOK_BLOCK_MS',
  readinessTimeoutMs: 'READINESS_TIMEOUT_MS',
  workerHeartbeatIntervalMs: 'WORKER_HEARTBEAT_INTERVAL_MS',
  schedulerHeartbeatIntervalMs: 'SCHEDULER_HEARTBEAT_INTERVAL_MS',
  processHeartbeatTtlSeconds: 'PROCESS_HEARTBEAT_TTL_SECONDS',
  healthSnapshotSchedule: 'HEALTH_SNAPSHOT_SCHEDULE',
  operationsPruneSchedule: 'OPERATIONS_PRUNE_SCHEDULE',
  healthHistoryRetentionDays: 'HEALTH_HISTORY_RETENTION_DAYS',
  appUrl: 'APP_URL',
  frontendUrl: 'FRONTEND_URL',
  betterAuthUrl: 'BETTER_AUTH_URL',
  betterAuthSecret: 'BETTER_AUTH_SECRET',
  betterAuthTrustedOrigins: 'BETTER_AUTH_TRUSTED_ORIGINS',
  betterAuthSessionExpiresInSeconds: 'BETTER_AUTH_SESSION_EXPIRES_IN_SECONDS',
  betterAuthSessionUpdateAgeSeconds: 'BETTER_AUTH_SESSION_UPDATE_AGE_SECONDS',
  betterAuthVerificationExpiresInSeconds: 'BETTER_AUTH_VERIFICATION_EXPIRES_IN_SECONDS',
  betterAuthPasswordResetExpiresInSeconds: 'BETTER_AUTH_PASSWORD_RESET_EXPIRES_IN_SECONDS',
  betterAuthMinPasswordLength: 'BETTER_AUTH_MIN_PASSWORD_LENGTH',
  betterAuthMaxPasswordLength: 'BETTER_AUTH_MAX_PASSWORD_LENGTH',
  emailProvider: 'EMAIL_PROVIDER',
  resendApiKey: 'RESEND_API_KEY',
  mailFromAddress: 'MAIL_FROM_ADDRESS',
  mailFromName: 'MAIL_FROM_NAME',
} as const;

export const APP_ENVIRONMENTS = ['development', 'test', 'production'] as const;

export const APP_ENVIRONMENT = {
  development: APP_ENVIRONMENTS[0],
  test: APP_ENVIRONMENTS[1],
  production: APP_ENVIRONMENTS[2],
} as const;

export const DATABASE_DEFAULTS = {
  poolMax: 10,
  poolIdleTimeoutMs: 30_000,
  poolConnectionTimeoutMs: 5_000,
} as const;
